# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sslproject', '0002_auto_20171109_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='avatar',
            field=models.ImageField(default='sslproject/static/pic_folder/None/no-img.jpg', upload_to='sslproject/static/pic_folder/'),
        ),
    ]
