# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 07:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sslproject', '0005_auto_20171113_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='current_institute',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='mobileNo',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='year_of_joining',
        ),
    ]
