# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sslproject', '0012_employee_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
