# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 13:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sslproject', '0014_teaching'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaching',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='teaching',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
