# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sslproject', '0019_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='sponser',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='projects',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
