# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sslproject', '0022_achievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievements',
            name='details',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
