# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sslproject', '0024_auto_20171116_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='year',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
